WIP split protected areas dataset into multiple layers.
Currently failing:

```
ERROR: [pid 345] Worker Worker(salt=288784454, workers=1, host=52c86fae6a34, username=root, pid=345) failed    Ogr2OgrVector(requires_task=FetchOgrRemoteData(dataset_cfg={"id": "nunagis", "access_method": "ogr_remote_vector", "metadata": {"title": "TBD", "abstract": "TBD", "citation": {"text": "TBD", "url": "http://example.com/TBD"}}}, source_cfg={"id": "protected_areas", "query_url": "https://kort.nunagis.gl/server/rest/services/Hosted/Bird_important_areas/FeatureServer/0/query?f=json&where=true&outFields=*&orderByFields=fid0+ASC"}), layer_id=unesco_world_heritage_sites)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/opt/conda/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/luigi/tasks/qgreenland/qgreenland/tasks/common/vector.py", line 67, in run
    ogr2ogr(infile, outfile, **ogr2ogr_kwargs)
  File "/luigi/tasks/qgreenland/qgreenland/util/vector.py", line 46, in ogr2ogr
    raise RuntimeError(result.stderr)
RuntimeError: b'ERROR 1: "UNESCO%" not recognised as an available field.\nERROR 1: SetAttributeFilter("type" LIKE "UNESCO%") on layer \'valid\' failed.\n'
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Ogr2OgrVector_unesco_world_her_FetchOgrRemoteDa_27b476bdda   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 7
INFO: [pid 345] Worker Worker(salt=288784454, workers=1, host=52c86fae6a34, username=root, pid=345) running   Ogr2OgrVector(requires_task=FetchOgrRemoteData(dataset_cfg={"id": "nunagis", "access_method": "ogr_remote_vector", "metadata": {"title": "TBD", "abstract": "TBD", "citation": {"text": "TBD", "url": "http://example.com/TBD"}}}, source_cfg={"id": "protected_areas", "query_url": "https://kort.nunagis.gl/server/rest/services/Hosted/Bird_important_areas/FeatureServer/0/query?f=json&where=true&outFields=*&orderByFields=fid0+ASC"}), layer_id=walrus)
DEBUG: Executing ogr2ogr command: . activate gdal &&  ogr2ogr -makevalid  /luigi/data/luigi-wip/wip/walrus/transform-luigi-tmp-8235307942/valid.shp /input/nunagis.protected_areas/fetched.geojson
DEBUG: Executing ogr2ogr command: . activate gdal &&  ogr2ogr -lco ENCODING=UTF-8 -t_srs EPSG:3413 -clipdst /luigi/tasks/qgreenland/qgreenland/assets/local_data/greenland_rectangle.geojson -where "\"type\" LIKE \"Walrus%\"" /luigi/data/luigi-wip/wip/walrus/transform-luigi-tmp-8235307942/walrus.shp /luigi/data/luigi-wip/wip/walrus/transform-luigi-tmp-8235307942/valid.shp
ERROR: [pid 345] Worker Worker(salt=288784454, workers=1, host=52c86fae6a34, username=root, pid=345) failed    Ogr2OgrVector(requires_task=FetchOgrRemoteData(dataset_cfg={"id": "nunagis", "access_method": "ogr_remote_vector", "metadata": {"title": "TBD", "abstract": "TBD", "citation": {"text": "TBD", "url": "http://example.com/TBD"}}}, source_cfg={"id": "protected_areas", "query_url": "https://kort.nunagis.gl/server/rest/services/Hosted/Bird_important_areas/FeatureServer/0/query?f=json&where=true&outFields=*&orderByFields=fid0+ASC"}), layer_id=walrus)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/opt/conda/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/luigi/tasks/qgreenland/qgreenland/tasks/common/vector.py", line 67, in run
    ogr2ogr(infile, outfile, **ogr2ogr_kwargs)
  File "/luigi/tasks/qgreenland/qgreenland/util/vector.py", line 46, in ogr2ogr
    raise RuntimeError(result.stderr)
RuntimeError: b'ERROR 1: "Walrus%" not recognised as an available field.\nERROR 1: SetAttributeFilter("type" LIKE "Walrus%") on layer \'valid\' failed.\n'
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Ogr2OgrVector_walrus_FetchOgrRemoteDa_2c9381988c   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 7 pending tasks possibly being run by other workers
DEBUG: There are 7 pending tasks unique to this worker
DEBUG: There are 7 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=288784454, workers=1, host=52c86fae6a34, username=root, pid=345) was stopped. Shutting down Keep-Alive thread
INFO:
===== Luigi Execution Summary =====

Scheduled 276 tasks of which:
* 131 complete ones were encountered:
    - 24 BuildRasterOverviews(...)
    - 1 FetchDataFiles(...)
    - 1 FetchOgrRemoteData(...)
    - 1 GdalEdit(...)
    - 83 Ogr2OgrVector(...)
    ...
* 138 ran successfully:
    - 5 AncillaryFile(src_filepath=/luigi/tasks/qgreenland/CHANGELOG.md, dest_relative_filepath=CHANGELOG.txt) ...
    - 1 ArcticVegetation(layer_id=vegetation_biomass_2010)
    - 1 BackgroundImage(layer_id=background)
    - 1 BasalThermalState(layer_id=basal_thermal_state)
    - 4 BedMachineDataset(layer_id=bedmachine_bed,bedmachine_errbed,bedmachine_surface,bedmachine_thickness)
    ...
* 2 failed:
    - 2 Ogr2OgrVector(...)
* 5 were left pending, among these:
    * 5 had failed dependencies:
        - 1 CreateQgisProjectFile()
        - 1 IngestAllLayers()
        - 2 OgrRemoteVector(layer_id=unesco_world_heritage_sites,walrus)
        - 1 ZipQGreenland()

This progress looks :( because there were failed tasks
```