use `https` without certificate verification for arctic_dem fetch
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='data.pgc.umn.edu', port=443): Max retries exceeded with url: /elev/dem/setsm/ArcticDEM/mosaic/v3.0/100m/arcticdem_mosaic_100m_v3.0.tif (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
```